trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.6.0'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

# ✅ Authenticate to Azure using the service connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'jason-sc'  # Replace with your actual service connection name if necessary
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Init and apply
      terraform init -reconfigure
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan


#  - task: TerraformTask@5
#   inputs:
#     provider: 'azurerm'
#     command: 'init'
#     backendServiceArm: 'jason-sc'
#     backendAzureRmResourceGroupName: 'j64364-tfstate-rg'
#     backendAzureRmStorageAccountName: 'j64364sa'
#     backendAzureRmContainerName: 'tfstate'
#     backendAzureRmKey: 'terraform.tfstate'





